### ISSUE TITLE
final launch checklist

### ISSUE THREAD

**Issue by derekeder** [datamade/my-reps-pbp#6]
## Framing / Call to Action
- [ ] Make sure that the site has a clear call to action. This should not be 'hey look at this cool tool'. Rather, it should be a way for someone to engage in a meaningful way on the issue being presented.
## Web Search Indexing
- [ ] If you have a staging site, tell the search engine robots not to index you with a robots.txt
- [ ] Make sure you allow indexing when you are ready to launch.
## Google Analytics
- [ ] Create [Google Analytics](http://www.google.com/analytics/) account
- [ ] Hook up the GA Tracking Code (typically in our `analytics_lib.js` file)
- [ ] Set up relevant Goals and Funnels
- [ ] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en)
- [ ] Verify site in Webmaster Tools with DNS TXT record
- [ ] Link Webmaster Tools to Google Analytics
## Sharing & Rich Snippets
- [x] Set up general meta tags
  - `<meta name=“description”>`
  - `<meta name=“author”>`
- [x] Set up Facebook meta tags & validate [here](https://developers.facebook.com/tools/debug/)
  - `<meta property=“og:site_name”>`
  - `<meta property=“og:title”>`
  - `<meta property=“og:type”>`
  - `<meta property=“og:description”>`
  - `<meta property=“og:url”>`
  - `<meta property=“og:image”>`
- [x] Set up Twitter meta tags & validate [here](https://cards-dev.twitter.com/validator)
  - `<meta name=“twitter:card”>`
  - `<meta name=“twitter:site”>`
  - `<meta name=“twitter:creator”>`
  - `<meta name=“twitter:description”>` (note that this needs to be under 200 characters)
  - `<meta name=“twitter:title”>`
  - `<meta name=“twitter:url”>`
  - `<meta name=“twitter:image:src”>`
- [ ] Create 2-5 meme images using [Canva](http://canva.com/) or a similar tool
## Mobile Friendliness

Test on various mobile devices:
- [x] scrolling is easy
- [x] nav bar works
- [x] hoverable things are tappable
- [x] charts/maps look ok
## Page Speed
- [x] run the site through https://developers.google.com/speed/pagespeed/insights/
## Miscellaneous Polish
- [ ] add favicons, apple touch icons (http://www.favicomatic.com/)
- [x] add 404 & 500 error pages
## Testing
- [ ] Plan for a day of bugfixing. This day should happen after you have added the last features you plan on adding.
## GitHub Readme

If the site is open source, make sure the Readme.md is complete and accurate. 

Here's a few good examples:
- [Geomancer](https://github.com/associatedpress/geomancer/blob/master/README.md)
- [Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/README.md)

The Readme should have the following sections:
- [x] Overview
- [x] Setup
- [x] Running locally
- [x] Team
- [x] Errors / Bugs 
- [x] Pull Requests
- [x] Copyright and License
## Outreach
- [ ] Write up press release
- [ ] Identify who will be the primary person of contact and make their info prominent on the website and all PR
- [ ] Identify relevant media contacts to email
- [ ] Identify relevant social news sites (reddit, listservs, slack channels)
- [ ] Divide & conquer - send out the media blitz!
